<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
    <Authors>BitcoderCZ</Authors>
    <RepositoryUrl>https://github.com/Earth-Restored/Minecraft_Earth_Patcher</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.4.0</Version>
  </PropertyGroup>
</Project>
